CREATE DATABASE IF NOT EXISTS OP;

CREATE TABLE OP.USER_LOGIN (
    ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    IS_DELETED VARCHAR(1) NOT NULL DEFAULT 'N',
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    CREATED_BY INT(10) NULL DEFAULT NULL,
    CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY INT(10) NULL DEFAULT NULL,
    MODIFIED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX NAME (NAME)
)ENGINE=InnoDB;

CREATE TABLE OP.SUPPLIER (
    ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(40) NOT NULL,
    CONTACT VARCHAR(15),
    CREATED_BY INT(10) NULL DEFAULT NULL,
    CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY INT(10) NULL DEFAULT NULL,
    MODIFIED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N',
    INDEX FK_SUPPLIER_USER_LOGIN (CREATED_BY),
    CONSTRAINT FK_SUPPLIER_USER_LOGIN FOREIGN KEY (CREATED_BY) REFERENCES OP.USER_LOGIN (ID),
    INDEX FK_SUPPLIER_USER_LOGIN1 (MODIFIED_BY),
    CONSTRAINT FK_SUPPLIER_USER_LOGIN1 FOREIGN KEY (MODIFIED_BY) REFERENCES OP.USER_LOGIN (ID)
)ENGINE=InnoDB;

CREATE TABLE OP.CUSTOMER (
    ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUST_NAME VARCHAR(40) NOT NULL,
    CUST_LOCATION VARCHAR(40),
    CUST_PHONE VARCHAR(15),
    CUST_EMAIL VARCHAR(30),
    CREATED_BY INT(10) NULL DEFAULT NULL,
    CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY INT(10) NULL DEFAULT NULL,
    MODIFIED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N',
    INDEX FK_CUSTOMER_USER_LOGIN (CREATED_BY),
    CONSTRAINT FK_CUSTOMER_USER_LOGIN FOREIGN KEY (CREATED_BY) REFERENCES OP.USER_LOGIN (ID),
    INDEX FK_CUSTOMER_USER_LOGIN1 (MODIFIED_BY),
    CONSTRAINT FK_CUSTOMER_USER_LOGIN1 FOREIGN KEY (MODIFIED_BY) REFERENCES OP.USER_LOGIN (ID)
)ENGINE=InnoDB;

CREATE TABLE OP.BUYLEADS (
    ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUST_ID INT(10) NOT NULL,
    STATUS VARCHAR(30),
    UNIQUECODE VARCHAR(50),
    FOLLOWUPCOUNT INT(2) DEFAULT 0,
    FOLLOWUPDATE TIMESTAMP NULL DEFAULT NULL,
    FOLLOWUPBY INT(10) NULL DEFAULT NULL,
    CREATED_BY INT(10) NULL DEFAULT NULL,
    CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY INT(10) NULL DEFAULT NULL,
    MODIFIED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N',
    INDEX FK_CUSTOMER_ID (CUST_ID),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUST_ID) REFERENCES OP.CUSTOMER (ID),
    INDEX FK_BUYLEADS_USER_LOGIN (CREATED_BY),
    CONSTRAINT FK_BUYLEADS_USER_LOGIN FOREIGN KEY (CREATED_BY) REFERENCES OP.USER_LOGIN (ID),
    INDEX FK_BUYLEADS_USER_LOGIN1 (MODIFIED_BY),
    CONSTRAINT FK_BUYLEADS_USER_LOGIN1 FOREIGN KEY (MODIFIED_BY) REFERENCES OP.USER_LOGIN (ID)
)ENGINE=InnoDB;

CREATE TABLE OP.BUYLEADSITEMS (
    ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BUYLEAD_ID INT(10) NOT NULL,
    ITEM_NAME VARCHAR(40) NOT NULL,
    QUANTITY INT(10),
    CATEGORY VARCHAR(15),
    RATE VARCHAR(10),
    GST VARCHAR(10),
    TOTAL VARCHAR(10),
    REMARKS VARCHAR(100),
    CREATED_BY INT(10) NULL DEFAULT NULL,
    CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY INT(10) NULL DEFAULT NULL,
    MODIFIED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N',
    INDEX FK_BUYLEAD_ID (BUYLEAD_ID),
    CONSTRAINT FK_BUYLEAD_ID FOREIGN KEY (BUYLEAD_ID) REFERENCES OP.BUYLEADS (ID),
    INDEX FK_BUYLEADSITEMS_USER_LOGIN (CREATED_BY),
    CONSTRAINT FK_BUYLEADSITEMS_USER_LOGIN FOREIGN KEY (CREATED_BY) REFERENCES OP.USER_LOGIN (ID),
    INDEX FK_BUYLEADSITEMS_USER_LOGIN1 (MODIFIED_BY),
    CONSTRAINT FK_BUYLEADSITEMS_USER_LOGIN1 FOREIGN KEY (MODIFIED_BY) REFERENCES OP.USER_LOGIN (ID)
)ENGINE=InnoDB;

CREATE TABLE OP.PROCURALITEMS (
    ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BUYLEAD_ID INT(10) NOT NULL,
    ITEM_NAME VARCHAR(40) NOT NULL,
    QUANTITY INT(10),
    SUPPLIER_ID INT(10),
    STATUS VARCHAR(30),
    CREATED_BY INT(10) NULL DEFAULT NULL,
    CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY INT(10) NULL DEFAULT NULL,
    MODIFIED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N',
    INDEX FK_SUPPLIER_ID (SUPPLIER_ID),
    CONSTRAINT FK_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES OP.SUPPLIER (ID),
    INDEX FK_PROCURALITEMS_USER_LOGIN (CREATED_BY),
    CONSTRAINT FK_PROCURALITEMS_USER_LOGIN FOREIGN KEY (CREATED_BY) REFERENCES OP.USER_LOGIN (ID),
    INDEX FK_PROCURALITEMS_USER_LOGIN1 (MODIFIED_BY),
    CONSTRAINT FK_PROCURALITEMS_USER_LOGIN1 FOREIGN KEY (MODIFIED_BY) REFERENCES OP.USER_LOGIN (ID)
)ENGINE=InnoDB;